services:
  frontend:
    build: .
    container_name: quantum-frontend
    ports:
      - "5185:5185" # Modified to match Dockerfile exposed port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://host.docker.internal:8000 # Use special DNS name to access host machine
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes
      - WATCHPACK_POLLING=true # webpack file watching
    extra_hosts:
      - "host.docker.internal:host-gateway" # Add host.docker.internal resolution
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
