version: "3.8"

services:
  fastapi:
    build:
      context: ./FastAPI_app
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "erik"
      RABBITMQ_PASS: "erik"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: erik
      RABBITMQ_DEFAULT_PASS: erik
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
