services:
  fastapi:
    image: python:3.11-slim
    container_name: fastapi
    working_dir: /app/FastAPI_app
    volumes:
      - .:/app/FastAPI_app
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
      MONGO_URI: "mongodb://host.docker.internal:27017/"
      RABBITMQ_HOST: "host.docker.internal"
      RABBITMQ_USER: "erik"
      RABBITMQ_PASS: "erik"
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             uvicorn FastAPI_app.main:app --host 0.0.0.0 --port 8000"
