services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./MongoDB/init:/docker-entrypoint-initdb.d:ro
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: Quantum-Encoding-DB

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: erik
      RABBITMQ_DEFAULT_PASS: erik
    volumes:
      - rabbitmq_data:/data/rabbitmq

  fastapi:
    image: python:3.11-slim
    container_name: fastapi
    working_dir: /app/FastAPI_app
    volumes:
      - ./FastAPI_app:/app/FastAPI_app
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
      MONGO_URI: "mongodb://mongodb:27017/"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: "erik"
      RABBITMQ_PASS: "erik"
    depends_on:
      - mongodb
      - rabbitmq
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             uvicorn FastAPI_app.main:app --host 0.0.0.0 --port 8000"

volumes:
  mongo_data:
    driver: local
  rabbitmq_data:
    driver: local
