services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: Quantum-Encoding-DB

volumes:
  mongo_data:
